### ISSUE TITLE
Thread Support

### ISSUE THREAD

**Issue by wac2007** [botpress/botpress-botkit#2]
There's a way to use [Botkit Threads](https://github.com/howdyai/botkit#conversation-threads) in botpress-botkit? I tried to use createConversation and the function is undefined :/

**Comment by slvnperron** [comment]
@wac2007 thanks for reporting. There's the `startConversation` that works, we'll need to implement createConversation too

**Comment by slvnperron** [comment]
The fix is pretty simple though: https://github.com/botpress/botpress-botkit/blob/master/src/index.js#L138

**Comment by wac2007** [comment]
I will try here and submit a pull request if i can make it  :)

**Comment by wac2007** [comment]
Fixed in Pull Request #3
