### ISSUE TITLE
Full example fails

### ISSUE THREAD

**Issue by AdanTL** [botpress/botpress-botkit#4]
I've tried the full example provided and this is what I get:

> 15:14:01 - info: >   [Start]  0  Conversation with  <USER_ID> in facebook
15:14:01 - debug: No handler for conversationStarted
15:14:01 - debug: No handler for conversationStarted
15:14:01 - debug: Setting up a handler for end
15:14:01 - debug: No handler for stats:heard_trigger
15:14:02 - debug: No handler for tick
15:14:02 - error: [botpress] Unhandled error in middleware (outgoing), error: An error has been returned by Facebook API.
Status: 400 (Bad Request)
(#100) No matching user found

And no response.

**Comment by AdanTL** [comment]
@slvnperron still getting "No handler for tick" but, bot is working perfectly.

Thanks :+1:

**Comment by slvnperron** [comment]
Awesome! The "no handler" is from botkit unfortunately :(
